scorecard:
  # Setting a global scorecard option
  output: text
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/infra.watch_v1alpha1_serviceassurance_cr.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/infra.watch_v1alpha1_serviceassurance_cr.yaml"
        csv-path: "deploy/olm-catalog/service-assurance-operator/0.1.0/service-assurance-operator.v0.1.0.clusterserviceversion.yaml"
