apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "infra.watch/v1alpha1",
          "kind": "ServiceAssurance",
          "metadata": {
            "name": "cloud-serviceassurance"
          },
          "spec": {
            "events": {
              "enabled": true
            },
            "metrics": {
              "enabled": true
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Monitoring
    certified: "false"
    containerImage: quay.io/redhat-service-assurance/service-assurance-operator.0.1.0
    createdAt: "2019-11-04T08:00:00Z"
    description: Service Assurance Framework. Umbrella Operator for instantiating
      the required dependencies and configuration of various components to build a
      Service Assurance platform for telco grade monitoring.
    repository: https://github.com/redhat-service-assurance/service-assurance-operator
    support: Red Hat, Inc.
  name: service-assurance-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Represents an instance of the Service Assurance Framework
      displayName: SAF Cluster
      kind: ServiceAssurance
      name: serviceassurances.infra.watch
      version: v1alpha1
  description: Service Assurance Operator for monitoring clouds
  displayName: Service Assurance Operator
  install:
    spec:
      deployments:
      - name: service-assurance-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: service-assurance-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: service-assurance-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/redhat-service-assurance/service-assurance-operator.0.1.0
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: service-assurance-operator
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/redhat-service-assurance/service-assurance-operator.0.1.0
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: service-assurance-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - service-assurance-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - infra.watch
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: service-assurance-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - monitoring
  - serviceassurance
  links:
  - name: Source Code
    url: https://github.com/redhat-service-assurance/service-assurance-operator
  maintainers:
  - email: leif@redhat.com
    name: Leif Madsen
  maturity: alpha
  minKubeVersion: 1.13.0
  provider:
    name: Red Hat, Inc.
  version: 0.1.0
