apiVersion: infra.watch/v1alpha1
kind: ServiceAssurance
metadata:
  name: saf-default
spec:
  metricsEnabled: true
  eventsEnabled: false
  highAvailabilityEnabled: false
# vim: set ft=yaml shiftwidth=2 tabstop=2 expandtab:
