apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-assurance-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: service-assurance-operator
  template:
    metadata:
      labels:
        name: service-assurance-operator
    spec:
      serviceAccountName: service-assurance-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: quay.io/redhat-service-assurance/service-assurance-operator.0.1.0
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: quay.io/redhat-service-assurance/service-assurance-operator.0.1.0
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "service-assurance-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
