- name: Lookup template
  debug:
    msg: "{{ lookup('template', './manifest_elasticsearch.j2') }}"

- name: Set default ElasticSearch manifest
  set_fact:
    elasticsearch_manifest: "{{ lookup('template', './manifest_elasticsearch.j2') }}"
  when: elasticsearch_manifest is not defined

- name: Show ElasticSearch manifest being loaded
  debug:
    var: elasticsearch_manifest | from_yaml

- name: Show ElasticSearch manifest being loaded
  debug:
    var: elasticsearch_manifest | from_yaml

- name: Create an instance of ElasticSearch
  k8s:
    definition:
      '{{ elasticsearch_manifest }}'
