---
# set default enablement
metrics_enabled: true
events_enabled: false
high_availability_enabled: false

# default values
prometheus_storage_class: ""
prometheus_storage_resources: {}
prometheus_storage_selector: {}
prometheus_pvc_storage_request: 20G
qdr_deploymentplan_size: 1
elasticsearch_node_count: 1
# vim: set ft=yaml shiftwidth=2 tabstop=2 expandtab:
