# ---
# Build out initial selfsigning issuer
# ----
- name: Create selfsigned Issuer
  k8s:
    definition:
      apiVersion: certmanager.k8s.io/v1alpha1
      kind: Issuer
      metadata:
        name: '{{ meta.name }}-selfsigned'
        namespace: '{{ meta.namespace }}'
      spec:
        selfSigned: {}

- name: Create default Certificate manifest for Elasticsearch
  set_fact:
    elasticsearch_certificate_manifest: |
      apiVersion: certmanager.k8s.io/v1alpha1
      kind: Certificate
      metadata:
        name: elasticsearch-es-cert
        namespace: '{{ meta.namespace }}'
      spec:
        dnsNames:
          - elasticsearch-es-http
          - elasticsearch-es-http.{{ meta.namespace }}.svc
          - elasticsearch-es-http.{{ meta.namespace }}.svc.cluster.local
        isCA: true
        issuerRef:
          kind: Issuer
          name: {{ meta.name }}-selfsigned
        secretName: elasticsearch-es-cert
  when: elasticsearch_certificate_manifest is not defined

- name: Create certificate for Elasticsearch
  k8s:
    definition:
      '{{ elasticsearch_certificate_manifest }}'
