- name: Create certificate
  k8s:
    definition:
      apiVersion: certmanager.k8s.io/v1alpha1
      kind: Certificate
      metadata:
        name: '{{ meta.namespace }}-{{ item.name }}'
        namespace: '{{ meta.namespace }}'
      spec:
        commonName: '{{ item.commonName }}'
        organization:
        - Logging
        secretName: '{{ meta.namespace }}-{{ item.name }}-credentials'
        dnsNames:
        - 127.0.0.1
        - localhost
        - elasticsearch
        - elasticsearch.cluster.local
        - 'elasticsearch.{{ meta.namespace }}.svc'
        - 'elasticsearch.{{ meta.namespace }}.cluster.local'
        - 'elasticsearch.{{ meta.namespace }}.svc.cluster.local'
        - elasticsearch-cluster
        - elasticsearch-cluster.cluster.local
        - 'elasticsearch-cluster.{{ meta.namespace }}.svc'
        - 'elasticsearch-cluster.{{ meta.namespace }}.cluster.local'
        - 'elasticsearch-cluster.{{ meta.namespace }}.svc.cluster.local'
        issuerRef:
          kind: Issuer
          name: '{{ meta.namespace }}-ca'

- name: Get secret info
  k8s_facts:
    api_version: v1
    kind: Secret
    name: '{{ meta.namespace }}-{{ item.name }}-credentials'
    namespace: '{{ meta.namespace }}'
  register: _this_credentials

- name: Set variable containing drilled down certificate files
  set_fact:
    "secret_{{ item.name }}_credentials": "{{ _this_credentials.resources | first }}"
