- name: Create default Events Smart Gateway manifest
  set_fact:
    smartgateway_events_manifest: |
      apiVersion: smartgateway.infra.watch/v2alpha1
      kind: SmartGateway
      metadata:
        name: '{{ meta.name }}-notification'
        namespace: '{{ meta.namespace }}'
      spec:
        size: 1
        amqp_url: '{{ meta.name }}-interconnect.{{ meta.namespace }}.svc.cluster.local:5672/collectd/notify'
        service_type: 'events'
        debug: 'true'
        elastic_url: 'https://elasticsearch.{{ meta.namespace }}.svc.cluster.local:9200'
        container_image_path: 'quay.io/redhat-service-assurance/smart-gateway:latest'
        use_tls: 'true'
        tls_client_cert: /config/certs/admin-cert
        tls_client_key: /config/certs/admin-key
        tls_ca_cert: /config/certs/admin-ca
        tls_server_name: 'elasticsearch.{{ meta.namespace }}.svc.cluster.local'
        reset_index: 'true'
  when: smartgateway_events_manifest is not defined

- name: Deploy instance of Smart Gateway for Events
  k8s:
    definition:
      '{{ smartgateway_events_manifest }}'
