- name: Deploy instance of Smart Gateway
  k8s:
    definition:
      apiVersion: smartgateway.infra.watch/v2alpha1
      kind: SmartGateway
      metadata:
        name: '{{ meta.name }}-smartgateway'
        namespace: '{{ meta.namespace }}'
      spec:
        amqp_url: '{{ meta.name }}-interconnect.{{ meta.namespace }}.svc.cluster.local:5672/collectd/telemetry'
        container_image_path: 'quay.io/redhat-service-assurance/smart-gateway:latest'
        debug: 'true'
        service_type: 'metrics'
        size: 1
