- name: Set default Alertmanager manifest
  set_fact:
    alertmanager_manifest: |
      apiVersion: monitoring.coreos.com/v1
      kind: Alertmanager
      metadata:
        labels:
          alertmanager: '{{ meta.name }}'
        name: '{{ meta.name }}'
        namespace: '{{ meta.namespace }}'
      spec:
        replicas: 1
        ruleSelector: {}
        securityContext: {}
        serviceAccountName: prometheus-k8s
        serviceMonitorSelector:
          matchLabels:
            app: smart-gateway
        storage:
          class: {{ alertmanager_storage_class }}
          resources: {{ alertmanager_storage_resources }}
          selector: {{ alertmanager_storage_selector }}
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: {{ alertmanager_pvc_storage_request }}
  when: alertmanager_manifest is not defined

- name: Create an instance of Alertmanager
  k8s:
    definition:
      '{{ alertmanager_manifest }}'

# TODO: Create route to access Alertmanager (conditional, default off)
