- name: Set default ElasticSearch manifest
  set_fact:
    elasticsearch_manifest: |
      apiVersion: logging.openshift.io/v1
      kind: Elasticsearch
      metadata:
        name: elasticsearch
        namespace: '{{ meta.namespace }}'
      spec:
        managementState: Managed
        nodeSpec:
          image: registry.redhat.io/openshift4/ose-logging-elasticsearch5:v4.2.8
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 1Gi
        redundancyPolicy: {{ elasticsearch_redundancy_policy }}
        nodes:
          - nodeCount: {{ elasticsearch_node_count }}
            roles:
              - client
              - data
              - master
            storage:
              storageClassName: ""
              size: 10Gi
  when: elasticsearch_manifest is not defined

- name: Create an instance of ElasticSearch
  k8s:
    definition:
      '{{ elasticsearch_manifest }}'
