- name: Set default ElasticSearch manifest
  set_fact:
    elasticsearch_manifest: |
      apiVersion: elasticsearch.k8s.elastic.co/v1beta1
      kind: Elasticsearch
      metadata:
        name: elasticsearch
        namespace: '{{ meta.namespace }}'
      spec:
        http:
          tls:
            certificate:
              secretName: 'elasticsearch-es-cert'
        nodeSets:
          - config:
              node.data: true
              node.ingest: true
              node.master: true
              node.store.allow_mmap: false
            count: {{ elasticsearch_node_count }}
            name: default
            podTemplate:
              spec:
                containers:
                  - name: elasticsearch
                    resources:
                      limits:
                        cpu: '2'
                        memory: 4Gi
                      requests:
                        cpu: '1'
                        memory: 4Gi
                volumes:
                  - emptyDir: {}
                    name: elasticsearch-data
        version: 7.5.1
  when: elasticsearch_manifest is not defined

- name: Create an instance of ElasticSearch
  k8s:
    definition:
      '{{ elasticsearch_manifest }}'
