---
- name: Create QDR instance
  include_tasks: component_qdr.yml

- name: Execute default tasks when metrics are requested to be enabled
  include_tasks: sa_metrics.yml
  when: metrics_enabled

- name: Execute default tasks when events are requested to be enabled
  include_tasks: sa_events.yml
  when: events_enabled
