#- name: Setup Certificates for ElasticSearch
#  include_tasks: component_certificates.yml

#- name: Setup ElasticSearch
#  include_tasks: component_elasticsearch.yml

- name: Create Smart Gateway instance
  include_tasks: component_events_smartgateway.yml
