name: CI
on: push

jobs:

  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo and switch to corresponding pull request
        uses: actions/checkout@v3

      - name: Schedule test on Testing Farm
        uses: sclorg/testing-farm-as-github-action@v1
        with:
          api_key: ${{ secrets.TESTING_FARM_API_TOKEN }}
          git_url: https://gitlab.cee.redhat.com/cloudops/testing-farm-tests.git
          git_ref: lmadsen-hello-world
          compose: CentOS-Stream-8
          pull_request_status_name: "STF Testing Farm"
          tf_scope: private
