name: CI
on: push

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: python -m pip install 'ansible <= 2.9'

      - name: Install operator_sdk.util dependency for Ansible role linting
        run: ansible-galaxy collection install 'operator_sdk.util >= 0.4.0'

      - name: Install ansible-lint
        run: pip install 'ansible-lint < 6.0.0'

      - name: Lint Ansible roles/servicetelemetry/ directory
        run: ${HOME}/.local/bin/ansible-lint roles/servicetelemetry

  build-operator-check:
    name: Build Operator check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify image builds
        run: make docker-build IMG="infrawatch/service-telemetry-operator:latest"

  build-bundle-check:
    name: Build bundle check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify image builds
        run: make bundle bundle-build

  check-bundle-validation-scorecard:
    name: Validate the generated bundle and perform scorecard checks
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # generate the bundle
      - name: Generate bundle
        run: make bundle

      # perform bundle validation
      - name: Check bundle validation
        run: operator-sdk bundle validate --verbose ./bundle

      - name: Create KinD cluster to execute scorecard tests
        uses: helm/kind-action@v1.4.0

      # perform scorecard checks against a KinD cluster
      - name: Check scorecord validation
        run: operator-sdk scorecard --verbose ./bundle
